[workspace]
members = [
    "docgen",
    "drivers/ahcid",
    "drivers/bgad",
    "drivers/e1000d",
    "drivers/nvmed",
    "drivers/pcid",
    "drivers/ps2d",
    "drivers/rtl8168d",
    "drivers/vboxd",
    "drivers/vesad",
    "drivers/xhcid",
    "installer",
    "kernel",
    "programs/acid",
    "programs/contain",
    "programs/coreutils",
    "programs/extrautils",
    "programs/init",
    "programs/ion",
    "programs/netutils",
    "programs/orbutils",
    "programs/pkgutils",
    "programs/smith",
    "programs/tar",
    "programs/timeout",
    "programs/userutils",
    "schemes/ethernetd",
    "schemes/ipd",
    "schemes/orbital",
    "schemes/ptyd",
    "schemes/randd",
    "schemes/redoxfs",
    "schemes/tcpd",
    "schemes/udpd"
]

[replace]
"jpeg-decoder:0.1.12" = { path = "libs/jpeg-decoder" }
"orbclient:0.3.3" = { path = "libs/orbclient" }
"orbfont:0.1.7" = { path = "libs/orbfont" }
"orbimage:0.1.15" = { path = "libs/orbimage" }
"orbtk:0.2.19" = { path = "libs/orbtk" }
"termion:1.3.0" = { path = "libs/termion" }
