# This is the default configuration file

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false
sysroot = "build/initfs"

# Package settings
[packages]
drivers = {}
init = {}
redoxfs = {}

[[files]]
path="/etc/init.rc"
data="""
export PATH initfs:/bin
vesad T T G
stdio display:1
ps2d
pcid /etc/pcid.toml
redoxfs disk:0 file
cd file:
export PATH file:/bin
run.d /etc/init.d
"""

[[files]]
path="/etc/pcid.toml"
data="""
[[drivers]]
name = "AHCI storage"
class = 1
subclass = 6
command = ["ahcid", "$NAME", "$BAR5", "$IRQ"]

[[drivers]]
name = "NVME storage"
class = 1
subclass = 8
command = ["nvmed", "$NAME", "$BAR0", "$IRQ"]

[[drivers]]
name = "QEMU Graphics Array"
class = 3
vendor = 4660
device = 4369
command = ["bgad", "$NAME", "$BAR0"]

[[drivers]]
name = "VirtualBox Graphics Array"
class = 3
vendor = 33006
device = 48879
command = ["bgad", "$NAME", "$BAR0"]

[[drivers]]
name = "VirtualBox Guest Device"
class = 8
vendor = 33006
device = 51966
command = ["vboxd", "$NAME", "$BAR0", "$BAR1", "$IRQ"]
"""
