[package]
name = "arch_x86_64"
version = "0.1.0"

[dependencies]
bitflags = "*"
hole_list_allocator = { path = "../../alloc/hole_list_allocator" }
io = { path = "../../drivers/io" }
spin = "*"

[dependencies.x86]
version = "*"
default-features = false
